id: P2D54C212
initial_creation_type: input
source_metadata:
  title: Tārānamaskāraikaviṃśatistotra
  language: sa
  volumes:
    de691b6cfda24e55ae0dcd1fabefd68b:
      title: .txt
      base_file: .txt.txt
      work_id: W6A5387A5
  chapter_to_tile: {}
created_at: '2022-03-01T23:40:12.514851'
last_modified_at: '2022-03-01T23:40:12.514858'
